openapi: 3.1.0
info:
  title: ES-ERP API
  version: "1.0"
paths:
  /api/readyz:
    get:
      operationId: GetApiReadyz
      summary: Readiness
      description: Readiness
      responses:
        "200":
          description: GET /api/readyz Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                required:
                  - status
                  - data
        "400":
          description: GET /api/readyz Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
  /api/folders/command:
    post:
      operationId: PostApiFoldersCommand
      summary: Folder Commands
      description: Folder Commands
      requestBody:
        description: POST /api/folders/command Request body
        content:
          application/json:
            schema:
              allOf:
                - type: object
                - oneOf:
                    - type: object
                      properties:
                        type:
                          type: string
                          const: create_folder
                        name:
                          type: string
                      required:
                        - type
                        - name
                    - type: object
                      properties:
                        type:
                          type: string
                          const: rename_folder
                        name:
                          type: string
                        _id:
                          type: string
                      required:
                        - type
                        - name
                        - _id
      security:
        - APIKEY_1: []
      responses:
        "200":
          description: POST /api/folders/command Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                    required:
                      - _id
                      - name
                required:
                  - status
                  - data
        "400":
          description: POST /api/folders/command Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    APIKEY_1:
      type: apiKey
      in: header
      name: Authorization
  links: {}
  callbacks: {}
tags: []
servers:
  - url: http://localhost:5000
