openapi: 3.1.0
info:
  title: ES-ERP API
  version: "1.0"
paths:
  /api/readyz:
    get:
      operationId: GetApiReadyz
      summary: Readiness
      description: Readiness
      responses:
        "200":
          description: GET /api/readyz Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                required:
                  - status
                  - data
        "400":
          description: GET /api/readyz Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
  /api/folders/command/create:
    get:
      operationId: GetApiFoldersCommandCreate
      summary: Readiness
      description: Readiness
      security:
        - APIKEY_1: []
      responses:
        "200":
          description: GET /api/folders/command/create Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                    properties:
                      user:
                        type: string
                    required:
                      - user
                required:
                  - status
                  - data
        "400":
          description: GET /api/folders/command/create Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    APIKEY_1:
      type: apiKey
      in: header
      name: Authorization
  links: {}
  callbacks: {}
tags: []
servers:
  - url: http://localhost:5000
